config/routes.rb
Info2310::Application.routes.draw do

  root to: 'static_pages#home'
  
  resources :microposts

  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]

  get "static_pages/home"

  get "static_pages/help"
  
  get "static_pages/about"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user

  attr_accessible :content, :user_id
  
  validates :user_id, presence: true
  
  validates :content, presence: true, length: { minimum: 5, maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name, :password, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" },
							:default_url => "/images/:style/missing.png"
  
  validates :password, presence: true, if: "hashed_password.blank?"
  
  validates :name, presence: true,
                      length: { minimum: 4, maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                        format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  
  has_many :microposts

  before_save :encrypt_password
                
  def encrypt_password
    self.salt ||= Digest::SHA256.hexdigest("--#{Time.now.to_s}- -#{email}--")
    self.hashed_password = encrypt(password)
  end

  def encrypt(raw_password)
    Digest::SHA256.hexdigest("--#{salt}--#{raw_password}--")
  end
  
  def self.authenticate(email, plain_text_password)
	user = User.find_by_email(email)
	if (user && user.hashed_password && user.hashed_password == user.encrypt(plain_text_password) ) then user else nil end
  end
  
  def feed(paginate_options={page: 1})
	microposts.paginate(paginate_options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  before_filter :redirect_unless_authorized, only: [:edit, :update, :destroy]
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.build(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
		format.js { render partial: 'microposts/show' }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
		format.js { render partial: 'microposts/errors' }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
	  format.js { render partial: 'microposts/destroy' }
    end
  end
  
  private
	def redirect_unless_authorized
		@micropost = Micropost.find(params[:id])
		@user = @micropost.user
		if @user != current_user
			flash[:error] = "You are not authorized to edit that Micropost"
			redirect_to root_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_filter :redirect_home_if_signed_in, only: [:new, :create]

  def new
  end

  def create
	user = User.authenticate(params[:session][:email], params[:session][:password])
	
	if user 
		flash[:notice] = "Welcome, #{user.email}!"
		sign_in(user)
		redirect_to user_path(user)
	else
		flash[:error] = "Invalid email/password combination"
		redirect_to new_session_path
	end
  end

  def destroy
	user = current_user
	flash[:notice] = "Logged out #{user.email}"
	sign_out_user
	redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
	  @micropost = Micropost.new
      @feed = current_user.feed(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :redirect_home_if_signed_in, only: [:new, :create]
  before_filter :redirect_unless_authorized, only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  
  
  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
	@microposts = @user.microposts.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  private 
	def redirect_unless_authorized
		@user = User.find(params[:id])
		if @user != current_user
			flash[:error] = "You are not authorized to edit that user"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "INFO2310 MicroPoster"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
  
  def sign_in(user)
    cookies[:current_user_id] = user.id
    self.current_user = user
  end

  def sign_out_user
    cookies.delete :current_user_id
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_id(cookies[:current_user_id])
  end

  def signed_in?
    !current_user.nil?
  end
  
  def redirect_home_if_signed_in
	redirect_to root_path if signed_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  
  <small>
    <%= link_to 'Rails Tutorial', 'http://railstutorial.org/' %>
    by Michael Hartl
  </small>
  | 
  <%= link_to "INFO2310", 'http://curails.herokuapp.com' %>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "Microposter", root_path, class: 'brand' %>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', static_pages_help_path %></li>
          <li><%= link_to 'About', static_pages_about_path %></li>
		  <li><%= link_to 'Users', users_path %></li>
		  <% if signed_in? %>
			<li><%= link_to 'My Profile', user_path(current_user) %></li>
			<li><%= link_to 'My Account', edit_user_path(current_user)%></li>
		    <li><%= link_to 'Logout', session_path(current_user), :method => :delete %></li>
		  <% else %>
		    <li><%= link_to 'Login', new_session_path %></li>
		  <% end %>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container"> 
  
	<% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %> 
	
    <%= yield %>
    <hr />
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/microposts/_destroy.js.erb
var nodename = "#micropost-<%= @micropost.id %>";

$(nodename).fadeOut(1000);
$(nodename).remove();

app/views/microposts/_errors.js.erb
var errors = $('<div class="alert alert-error"/>');

<% @micropost.errors.full_messages.each do |error| %>
  errors.append('<p><%= j(error) %></p>');
<% end %>

// Display errors before the form
$('#new_micropost').prepend(errors);
errors.fadeOut(3000);

app/views/microposts/_form.html.erb
<%= form_for(@micropost, remote: true) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<p id="micropost-<%= micropost.id %>">
  <span class='micropost_timestamp'>
     <%= micropost.created_at.strftime("%m/%d %l-%M") %>
   </span> 
   <%= micropost.content %>
   <% if current_user == micropost.user %> 
	<%= link_to 'Destroy', micropost, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
   <% end %>
</p>

app/views/microposts/_show.js.erb
// Get the HTML for a rendered MicroPost
var html = '<%= j(render(:partial => "micropost", :object => @micropost))%>';

// create a JQuery DOM element we can insert (and hide it so we can fade it in)
var element = $(html).hide();

// Add it to the user feed, and then fade it in
$('#user_feed').prepend(element);
element.fadeIn(1000);

// Reset the post input to empty
$('#new_micropost input[type="text"]').val('');

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.user_id %></td>
    <td><%= micropost.content %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class='row'>
  <div class='span12'>
    <h1>About</h1>
    <p>
      Like Twitter... but better
    </p>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class='row'>
  <div class='span12'>
    <h1>Help</h1>
    <p>
      Get help on the INFO2310 Microposter at 
      <a href="http://curails.herokuapp.com">the course website</a>
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="hero-unit">
  <h1>INFO 2310 Microposter</h1>
  <p>
    This is a sample website used in INFO 2310 to learn Ruby on Rails.  Please
    sign up and share your thoughts with us in 5-140 character chunks.
  </p>
  

	<% if signed_in? %>
		<%= render 'microposts/form' %>
	
		<%= will_paginate @feed %>
		<div id="user_feed">
			<%= render @feed %>
		</div>
		<%= will_paginate @feed %>
	<% else %>
	  <p>
		<%= link_to 'Sign Up', new_user_path, class: 'btn btn-primary btn-large' %>
	  </p>
	<% end %>


</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %> 
  <div class="field">
	<%= f.label :avatar %><br />
	<%= f.file_field :avatar %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>


<%= will_paginate @users %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  


<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
	<td><%= image_tag user.avatar.url(:thumb) %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>



</table>

<br />

<%= will_paginate @users %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Avatar:</b>
  <%= image_tag @user.avatar.url(:medium) %>
</p>

<p>
	<%= pluralize(@user.microposts.length, "Micropost") %>
</p>

<%= will_paginate @microposts %>
<%= render @microposts %>
<%= will_paginate @microposts %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>